[project]
name = "multiple-minimum-monte-carlo"
version = "0.0.15"
description = "Open source implementation of multiple minimum Monte Carlo"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ase",
    "rdkit",
    "rich",
    "scipy",
    "torch>=2.5.1",
]

authors = [ { name = "Nicholas Casetti" } ]
license = { file = "LICENSE" }

[project.scripts]
mcmm = "multiple_minimum_monte_carlo.mcmm:main"

[dependency-groups]
dev = [
    "aimnet ; python_full_version >= '3.11'",
    "build>=1.2.2.post1",
    "ipykernel",
    "pytest",
    "ruff",
    "twine",
]


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = { exclude = ["tests*"] } }

[tool.uv.sources]
aimnet = { git = "https://github.com/isayevlab/aimnetcentral.git" }
